services:
  # The main application (API services and front-end JavaScript)
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    ports:
      - 3000:3000

    env_file: "development.env"

    networks:
      - home-main

  # The mongo database service
  db:
    build:
      context: ./mongo
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - 27017:27017

    env_file: "development.env"

    volumes:
      - grid-of-words-data:/data/db/

    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 1m
      timeout: 15s
      retries: 2
      start_period: 10s

    networks:
      - home-main

volumes:
  grid-of-words-data:
    name: "grid-of-words-data"

# Uses the default home network (must be created first).
networks:
  home-main:
    external: true
