services:
  # The main application (API services and front-end JavaScript)
  grid-of-words-app:
    container_name: grid-of-words-app
    build:
      context: .
      target: prod
      dockerfile: Dockerfile

    env_file: "production.env"

    ports:
      - 3000:3000

    depends_on:
      grid-of-words-db:
        condition: service_healthy

    restart: always

    volumes:
      - ./data/certbot_etc:/etc/letsencrypt

    networks:
      - home-main

  # The mongo database service
  grid-of-words-db:
    container_name: grid-of-words-db
    image: mongo:6.0.18-rc0-jammy

    ports:
      - 27017:27017

    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 1m
      timeout: 15s
      retries: 2
      start_period: 10s

    env_file: "production.env"

    volumes:
      - ./scripts/mongoimport-words.sh:/docker-entrypoint-initdb.d/mongoimport-words.sh
      - ./data/words_english.txt:/data/words_english.txt
      - ./data/words_spanish.txt:/data/words_spanish.txt
      - grid-of-words-data:/data/db/

    networks:
      - home-main

volumes:
  grid-of-words-data:
    name: "grid-of-words-data"

# Uses the default home network (must be created first).
networks:
  home-main:
    external: true
